### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: MissingPluginException(No implementation found for method getPlatformVersion on channel com.jvhaile.broadcast_receiver/foreground)

### ISSUE THREAD

**Issue by UsabilitySpace** [jayvhaile/flutter_broadcast_receiver#1]
**When trying to run the example located here:**

- `[project_root]/example/lib/main.dart`

**... on Android Studio Emulator with the next two AVDs:** 

- `Nexus 5x API 25` = `Android SDK built for x86 (mobile)` = `qemu-system-i386` 
- `Nexus 5x API 28` = `AOSP on IA Emulator (mobile)` = `qemu-system-x86_64`

**... such an error occurs:** 

```
E/flutter (  471): [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: MissingPluginException(No implementation found for method getPlatformVersion on channel com.jvhaile.broadcast_receiver/foreground)
E/flutter (  471): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (  471): <asynchronous suspension>
E/flutter (  471): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (  471): #2      BroadcastReceiver.platformVersion (package:broadcast_receiver/src/broadcast_receiver.dart:15:43)
E/flutter (  471): #3      _MyAppState.initPlatformState (package:broadcast_receiver_example/main.dart:39:49)
E/flutter (  471): #4      _MyAppState.initState (package:broadcast_receiver_example/main.dart:30:10)
E/flutter (  471): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4704:58)
E/flutter (  471): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4540:5)
E/flutter (  471): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3508:14)
E/flutter (  471): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3266:18)
E/flutter (  471): #9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1252:16)
E/flutter (  471): #10     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1223:5)
E/flutter (  471): #11     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1165:17)
E/flutter (  471): #12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2626:19)
E/flutter (  471): #13     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1164:13)
E/flutter (  471): #14     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:974:7)
E/flutter (  471): #15     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:955:7)
E/flutter (  471): #16     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (  471): #17     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (  471): #18     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (  471): #19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (  471): #20     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (  471): #21     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (  471): #22     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (  471): #23     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (  471): #24     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (  471): #25     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (  471): #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**`Flutter pub get` has finished successfully with the next output:**

```
Running "flutter pub get" in master_000...                          1,1s
Running "flutter pub get" in example...                             0,8s
```

**`Flutter doctor -v` shows the next extended report:** 

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.36, on Mac OS X 10.15.6 19G73, locale ru-RU)
    • Flutter version 1.22.0-2.0.pre.36 at /Applications/flutter
    • Framework revision d30e36ba8c (3 days ago), 2020-08-21 22:36:03 -0400
    • Engine revision d495da20d0
    • Dart version 2.10.0 (build 2.10.0-49.0.dev)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/sergeglushenko/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.
 
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
    • AOSP on IA Emulator (mobile)       • emulator-5556 • android-x86 • Android 9 (API 28) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64  • Mac OS X 10.15.6 19G73

• No issues found!
```

**Android emulator version is:** 

- `30.0.26 (the latest stable version)`

**..., but the problem of the example has been showing on the previous stable version of Android emulator too.**

**Note that because of the exception described above, the example cannot correctly get the version of the platform it is running on, so the example shows:** 

- `Running on: Unknown`

**The picture of what the examples's main screen is showing is provided here:**

![image](https://user-images.githubusercontent.com/46682521/91158385-c0d5d480-e6f0-11ea-918c-b86d2b71602b.png)

**So, what may be the issue?**

**And what are the steps to correct that issue?**

**Comment by UsabilitySpace** [comment]
**To solve the issue in `Android Studio`, do the next 7 simple steps:**

**1. First of all:**

- `Stop the example app if it's running in Android Emulator.`

**2. Second, find & open the next file:** 

- `[project_root]/android/src/main/kotlin/com/jvhaile/broadcast_receiver/BroadcastReceiverPlugin.kt`

**3. Third, in file open find `onMethodCall` method of class `BroadcastReceiverPlugin`:** 

```
    override fun onMethodCall(@NonNull call: MethodCall, @NonNull result: Result) {
        if (call.method == "initialize") {
            SharedPreferenceHelper.saveCallbackDispatcherHandleKey(context, call.argument<Long>("callbackHandle")!!)
            result.success(null)
        } else {
            result.notImplemented()
        }
    }
```

**4. Fourth, replace found method `onMethodCall` method of class `BroadcastReceiverPlugin` with the next its new version:** 

```
    override fun onMethodCall(@NonNull call: MethodCall, @NonNull result: Result) {
        if (call.method == "initialize") {
            SharedPreferenceHelper.saveCallbackDispatcherHandleKey(context, call.argument<Long>("callbackHandle")!!)
            result.success(null)
        } else if (call.method == "getPlatformVersion"){ // ← ** add this line **
            result.success("Android " + android.os.Build.VERSION.RELEASE) // ← ** add this line **
        } else {
            result.notImplemented()
        }
    }
```

**5. Fifth, run next 4 commands in Android Studio project's command line in order to fully clean the project for the next build:** 

- `cd [project_root]`
- `flutter clean`
- `cd [project_root]/example`
- `flutter clean`

**6. And finally, run the project again in Android Emulator by pressing `Ctrl+R` or by pressing `triangle button on the project's toolbar`:**

![image](https://user-images.githubusercontent.com/46682521/91179469-baefeb80-e710-11ea-86e8-53f2ca7fc5dc.png)

**7. Don't forget, please, that Android Emulator should be running in order the project can be run in it.**
